# Site settings
title: Integration Craft
email: admin@integrationcraft.com
description: LabVIEW, Software and Test Systems Consultants> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
